### ISSUE TITLE
distutils error

### ISSUE THREAD

**Issue by imperialguy** [zopefoundation/BTrees#23]
```
(screening)NY120-14-143BX:~ vkarri$ pip install btrees
Collecting btrees
Downloading BTrees-4.2.0.tar.gz (209kB)
    100% |████████████████████████████████| 212kB 1.5MB/s
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/persistent/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'persistent' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: EOF occurred in violation of protocol (_ssl.c:590) -- Some packages may not be found!
    No local packages or download links found for persistent
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sg/sjflst_x7tg9zq115lqy0yrs5z65tg/T/pip-build-8sK7EZ/BTrees/setup.py", line 160, in <module>
        """
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/vkarri/pyenvs/screening/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/vkarri/pyenvs/screening/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/vkarri/pyenvs/screening/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/vkarri/pyenvs/screening/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/Users/vkarri/pyenvs/screening/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/Users/vkarri/pyenvs/screening/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/vkarri/pyenvs/screening/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('persistent')
```

**Comment by imperialguy** [comment]
proxy error on my machine
