### ISSUE TITLE
BTree.get(object()) raises TypeError on CPython, returns default on PyPy

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/BTrees#42]
I ran into an implementation difference between the C version and the Python versions.

Here's PyPy:
```python
Python 2.7.10 (7e8df3df9641, Jun 14 2016, 13:30:54)
[PyPy 5.3.1 with GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import BTrees
>>>> BTrees.OOBTree.OOBTree().get(object())
>>>>
```

Here's CPython:
```python
Python 2.7.12 (default, Jul 11 2016, 16:16:26)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import BTrees
>>> BTrees.OOBTree.OOBTree().get(object())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Object has default comparison
>>>
```

The specific type of object with default comparison doesn't really matter. And they both raise a TypeError if you try to set a key with default comparison (albeit with different error messages).

Which is the right behaviour here? I would argue that the Python behaviour is certainly nicer and friendlier to the user. It makes it easier to substitute a BTree for a dict in more places. In fact, on CPython, I had to subclass the BTree to be able to use it in place of a dict because of this TypeError (even though I had already made sure that we would never try to set such a value, sometimes we still query for them).

If there's consensus I can put together a PR to bring them into line.

**Comment by jamadden** [comment]
They have the same difference when it comes to the `in` operator: CPython raises TypeError, pure-Python returns False.

**Comment by jamadden** [comment]
They have a similar difference for non-integer keys in the int trees:
```python
Python 2.7.10 (7e8df3df9641, Jun 14 2016, 13:30:54)
[PyPy 5.3.1 with GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import BTrees
>>>> BTrees.family64.IO.BTree()['a key']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.tox/pypy/site-packages/BTrees/_base.py", line 1247, in __getitem__
    raise KeyError(key)
KeyError: 'a key'
```
vs
```python
Python 2.7.12 (default, Jul 11 2016, 16:16:26)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import BTrees
>>> BTrees.family64.IO.BTree()['a key']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected integer key
```

They both raise a TypeError for `in` in this case.

I'm working on a PR for this.
